title: "Xiaolin Lin"

author:
  name: Xiaolin Lin
  email: "linxiaolin593@gmail.com"



linkedin_username: linxiaolin
github_username: xiaolin593

url: "https://xiaolin593.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
assets: /assets/


# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /:title #replaces folder structure /YY/mm/dd/categories/title by only /title
